package com.codename1.demo.controllers;


import com.codename1.ui.controllers.ApplicationController;
import com.codename1.ui.controllers.ControllerEvent;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class ControllersDemo extends ApplicationController {

    
     @Override
    public void actionPerformed(ControllerEvent evt) {
        if (evt instanceof StartEvent) {
            evt.consume();
            new LoginController(this).getView().show();
            return;
        }
        
        if (evt instanceof LoginController.LoginSuccessfulEvent) {
            evt.consume();
            new MainFormController(this).getView().show();
            return;
        }
        super.actionPerformed(evt);
    }

}
